### ISSUE TITLE
atomic_flag有的项目里使用ATOMIC_FLAG_INIT初始化，两种方式区别是什么？

### ISSUE THREAD

**Issue by 52coder** [chronolaw/cpp_study#10]
https://github.com/chronolaw/cpp_study/blob/316e0bd2445c402567911b0b0618e03bfcf6af88/section5/SpinLock.hpp#L45

搜索了下ATOMIC_FLAG_INIT，c++20后这个宏被废弃，20前在使用，若标志拥有静态存储期，则此初始化为静态。老师能否帮忙解释下?
[https://zh.cppreference.com/w/cpp/atomic/ATOMIC_FLAG_INIT
](cppreference)

**Comment by chronolaw** [comment]
是的，这个宏已经不建议使用了，直接用花括号初始化就行了，具体的原因还没关注过，不过我觉得这个属于底层细节，意义不大。
