### ISSUE TITLE
c++filt -t 无法正确识别引用类型

### ISSUE THREAD

**Issue by 52coder** [chronolaw/cpp_study#11]
https://github.com/chronolaw/cpp_study/blob/316e0bd2445c402567911b0b0618e03bfcf6af88/section2/auto.cpp#L99
case6这里，我添加了如下代码
    cout << typeid(x3).name() <<endl;
    x1 = 10;
    cout << "x = "<< x <<" x1= "<< x1 << endl;

输出：
i
x = 10 x1= 10

[root c++]#c++filt -t i
int
这里c++filt -t视乎不能正确处理引用类型?

**Comment by chronolaw** [comment]
应该是typeid的问题，它取的名字不够准，用type_traits库吧。

   assert(std::is_lvalue_reference<decltype(x1)>::value);
    assert(std::is_pointer<decltype(x2)>::value);
    assert(std::is_lvalue_reference<decltype(x3)>::value);

**Comment by 52coder** [comment]
学习了，验证确实是这样。
