### ISSUE TITLE
for section5, cmake and make failed for luajit.h: No such file or directory

### ISSUE THREAD

**Issue by wilbyang** [chronolaw/cpp_study#12]
![image](https://user-images.githubusercontent.com/676318/111678386-849aca80-8820-11eb-8858-af6d884f1bb1.png)

**Comment by chronolaw** [comment]
需要预先安装luajit，可参考section4/luajit.cpp里的注释部分下载安装。
或者从GitHub上下载docker镜像，里面都安装好了。
docker pull chronolaw/cpp_study

**Comment by wilbyang** [comment]
> 需要预先安装luajit，可参考section4/luajit.cpp里的注释部分下载安装。
> 或者从GitHub上下载docker镜像，里面都安装好了。
> docker pull chronolaw/cpp_study

感谢chrono回复。我就是在docker pull chronolaw/cpp_study后的环境下跑的。整个过程如下
![image](https://user-images.githubusercontent.com/676318/111736666-94e19280-887e-11eb-8deb-29f60b362f8c.png)
另，这是我的系统环境
![image](https://user-images.githubusercontent.com/676318/111736762-bb9fc900-887e-11eb-8755-097c1db39f41.png)

**Comment by chronolaw** [comment]
可能是cmakelist写的不对，cmakelist是其他同学提供的。
我不是很熟悉cmake，一直是用gcc命令行直接编译的。可以直接用注释里的gcc命令试试。
