### ISSUE TITLE
Some examples not support c++11, but need at least c++14

### ISSUE THREAD

**Issue by matrixji** [chronolaw/cpp_study#3]
While trying to provide the makefile for example code under section2, I found some code are at least require c++14 standard, do you propose to support all code support c++11?

currently below examples under section2 need c++14:
- section2/auto.cpp
- section2/const.cpp
- section2/lambda.cpp

**Comment by chronolaw** [comment]
Thanks for your help.

These source are sample code for demo c++ feature, so I think we can just keep them.

And you could change them in your own fork as your wish.

**Comment by matrixji** [comment]
Got it.
