### ISSUE TITLE
g++ test.cpp -std=c++14 -I../common -o a.out;./a.out

### ISSUE THREAD

**Issue by yimao009** [chronolaw/cpp_study#8]
g++ test.cpp -std=c++14 -I../common -o a.out;./a.out

老师， 这个  -I../common 表示什么编译指令呀？

**Comment by program-spiritual** [comment]
https://linux.die.net/man/1/g++

**Comment by chronolaw** [comment]
指示包含路径，好像在专栏的留言里有解答的。
