### ISSUE TITLE
section5-->cpplang.hpp  static_assert 问题

### ISSUE THREAD

**Issue by 52coder** [chronolaw/cpp_study#9]
```
// static_assert
#if __cpp_static_assert >= 201411
#   define STATIC_ASSERT(x) static_assert(x)
#else
#   define STATIC_ASSERT(x) static_assert(x, #x)
#endif
```

这里为啥判断c++14?参考[cppreference](https://en.cppreference.com/w/cpp/language/static_assert)只有c++11和c++17有过改动，一个带提示信息，一个不带提示信息

**Comment by chronolaw** [comment]
这个是功能测试宏，不是c++14的版本号，参考https://zh.cppreference.com/w/cpp/feature_test
